package com.mymonstervr.kawabi.domain.model

data class Manga(
    val id: Long,
    val source: String,
    val siteKey: String?,
    val url: String,
    val title: String,
    val artist: String?,
    val author: String?,
    val description: String?,
    val genres: List<String>,
    val status: String,
    val thumbnailUrl: String?,
    val favorite: Boolean,
    val lastUpdate: Long?,
    val nextUpdate: Long?,
    val initialized: Boolean,
    val chapterFlags: Int,
    val viewer: Int,
    val dateAdded: Long,
    val calculateInterval: Int,
    val lastModifiedAt: Long,
    val version: Long,
    val isSyncing: Boolean,
    val totalChapters: Double,
    val notes: String,
    val lastReadAt: Long,
)
